package Commune.Dev.Models;

public enum AuditAction {
    CREATE_USER,
    UPDATE_NAME,
    UPDATE_EMAIL,
    CHANGE_ROLE,
    DISABLE_ACCOUNT,
    ENABLE_ACCOUNT,
    UPDATE_PROFILE,
    CHANGE_PASSWORD,
    UPDATE_ASSIGNMENT,
    DELETE_ACCOUNT
}
